name: 'remove-ansi-colors'
description: 'A GitHub action for removing ANSI color escape sequences from arbitrary strings'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  colored:
    description: 'The string containing ANSI color escape sequences'
outputs:
  uncolored:
    description: 'The string with ANSI color escape sequences removed'
    value: ${{ steps.ansi-code-removal.outputs.uncolored }}
runs:
  using: 'composite'
  steps:
    - id: ansi-code-removal
      run: |
        uncolored="$(echo "${{ inputs.colored }}" | perl -pe 's/\e\[[0-9;]*m//g'))"
        uncolored="${uncolored//'%'/'%25'}"
        uncolored="${uncolored//$'\n'/'%0A'}"
        uncolored="${uncolored//$'\r'/'%0D'}"
        echo "::set-output name=uncolored::$(echo "$uncolored")"
      shell: bash
