name: 'remove-ansi-colors'
description: 'A GitHub action for removing ANSI color escape sequences from arbitrary strings'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  colored:
    description: 'A string containing ANSI color escape sequences'
    required: true
outputs:
  uncolored:
    description: 'The string with ANSI color escape sequences removed'
    value: ${{ steps.ansi-code-removal.outputs.uncolored }}
runs:
  using: 'composite'
  steps:
    - id: ansi-code-removal
      run: |
        # Strip ANSI color escape sequences
        uncolored="$(echo "${{ inputs.colored }}" | perl -pe 's/\e\[[0-9;]*m//g')"

        # Replace line feed, carriage return, and percent sign with URL encoding
        # equivalents; will be substituted correctly in subsequent workflow steps
        # See: https://github.community/t/set-output-truncates-multiline-strings/16852/5
        uncolored="${uncolored//'%'/'%25'}"
        uncolored="${uncolored//$'\n'/'%0A'}"
        uncolored="${uncolored//$'\r'/'%0D'}"

        echo "uncolored=$uncolored" >> "$GITHUB_OUTPUT"
      shell: bash
